/* ======================================================
   JAISWAL FASHION — Product Data
   Mock database for all products, categories, and reviews
   ====================================================== */

// ==================== Categories ====================
const categories = [
  { id: 'tshirt', name: 'T-Shirts', icon: '👕', gradient: 'linear-gradient(135deg, #667eea, #764ba2)' },
  { id: 'lower', name: 'Lowers', icon: '👖', gradient: 'linear-gradient(135deg, #11998e, #38ef7d)' },
  { id: 'halfpant', name: 'Half Pants', icon: '🩳', gradient: 'linear-gradient(135deg, #f093fb, #f5576c)' },
  { id: 'jacket', name: 'Jackets', icon: '🧥', gradient: 'linear-gradient(135deg, #4facfe, #00f2fe)' },
  { id: 'hoodie', name: 'Hoodies', icon: '🔶', gradient: 'linear-gradient(135deg, #a18cd1, #fbc2eb)' },
  { id: 'kurta', name: 'Kurtas', icon: '👘', gradient: 'linear-gradient(135deg, #c8982e, #f5d799)' },
  { id: 'buluk', name: 'Bulk', icon: '🧶', gradient: 'linear-gradient(135deg, #8b0000, #cd5c5c)' },
  { id: 'sweater', name: 'Sweaters', icon: '🧶', gradient: 'linear-gradient(135deg, #e17055, #d63031)' },
];

// ==================== Color Swatches ====================
const colorOptions = [
  { name: 'Black', hex: '#1a1a1a' },
  { name: 'White', hex: '#f5f5f5' },
  { name: 'Navy Blue', hex: '#1e3a5f' },
  { name: 'Maroon', hex: '#6b1d1d' },
  { name: 'Olive Green', hex: '#4a5d23' },
  { name: 'Charcoal', hex: '#36454f' },
  { name: 'Royal Blue', hex: '#2b4ea0' },
  { name: 'Burgundy', hex: '#722f37' },
  { name: 'Mustard', hex: '#c8982e' },
  { name: 'Steel Gray', hex: '#71797e' },
  { name: 'Forest Green', hex: '#228b22' },
  { name: 'Wine Red', hex: '#722f37' },
];

// ==================== Size Options ====================
const sizeOptions = ['S', 'M', 'L', 'XL', 'XXL'];

// ==================== Products ====================
const localProducts = [
  // ---- T-SHIRTS ----
  {
    id: 'ts-001',
    name: 'Classic Round Neck T-Shirt',
    category: 'tshirt',
    price: 349,
    originalPrice: 599,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Maroon', hex: '#6b1d1d' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 128,
    description: 'Premium 100% combed cotton round neck t-shirt with bio-washed fabric for extra softness. Perfect for everyday casual wear.',
    material: '100% Combed Cotton, 180 GSM, Bio-Washed',
    fit: 'Regular Fit',
    washCare: 'Machine wash cold, Do not bleach, Tumble dry low',
    inStock: true,
    badge: 'Bestseller',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 'ts-002',
    name: 'Premium Polo T-Shirt',
    category: 'tshirt',
    price: 449,
    originalPrice: 799,
    colors: [
      { name: 'Royal Blue', hex: '#2b4ea0' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Olive Green', hex: '#4a5d23' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.3,
    reviewCount: 87,
    description: 'Stylish collar polo t-shirt with ribbed collar and cuffs. Ideal for semi-formal and casual occasions.',
    material: 'Cotton Pique, 220 GSM',
    fit: 'Slim Fit',
    washCare: 'Machine wash cold, Iron medium heat',
    inStock: true,
    badge: 'New',
    gradient: 'linear-gradient(135deg, #2b4ea0 0%, #667eea 100%)',
  },
  {
    id: 'ts-003',
    name: 'Printed Graphic T-Shirt',
    category: 'tshirt',
    price: 399,
    originalPrice: 699,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'White', hex: '#f5f5f5' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 203,
    description: 'Eye-catching graphic print t-shirt with HD quality printing that lasts 100+ washes. Urban street style design.',
    material: '100% Cotton, 160 GSM, Screen Printed',
    fit: 'Regular Fit',
    washCare: 'Turn inside out before washing, Machine wash cold',
    inStock: true,
    badge: 'Trending',
    gradient: 'linear-gradient(135deg, #36454f 0%, #1a1a1a 100%)',
  },
  {
    id: 'ts-004',
    name: 'V-Neck Premium T-Shirt',
    category: 'tshirt',
    price: 379,
    originalPrice: 649,
    colors: [
      { name: 'Burgundy', hex: '#722f37' },
      { name: 'Steel Gray', hex: '#71797e' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.2,
    reviewCount: 64,
    description: 'Elegant V-neck t-shirt crafted from premium cotton blend. Comfortable and stylish for any occasion.',
    material: 'Cotton-Lycra Blend, 190 GSM',
    fit: 'Slim Fit',
    washCare: 'Gentle machine wash, Hang dry',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #722f37 0%, #a04050 100%)',
  },

  // ---- LOWERS ----
  {
    id: 'lw-001',
    name: 'Classic Track Pants',
    category: 'lower',
    price: 449,
    originalPrice: 799,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Olive Green', hex: '#4a5d23' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.4,
    reviewCount: 156,
    description: 'Comfortable track pants with elastic waist and side pockets. Perfect for workouts, jogging, and lounging.',
    material: '100% Polyester, Moisture-Wicking',
    fit: 'Regular Fit',
    washCare: 'Machine wash cold, Do not iron on print',
    inStock: true,
    badge: 'Bestseller',
    gradient: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
  },
  {
    id: 'lw-002',
    name: 'Premium Joggers',
    category: 'lower',
    price: 549,
    originalPrice: 999,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Steel Gray', hex: '#71797e' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Olive Green', hex: '#4a5d23' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviewCount: 198,
    description: 'Premium jogger pants with ribbed cuffs and drawstring waist. Ultra-soft fleece interior for maximum comfort.',
    material: 'Cotton-Polyester Blend, French Terry, 300 GSM',
    fit: 'Slim Fit',
    washCare: 'Machine wash warm, Tumble dry low',
    inStock: true,
    badge: 'Popular',
    gradient: 'linear-gradient(135deg, #0f766e 0%, #14b8a6 100%)',
  },
  {
    id: 'lw-003',
    name: 'Cotton Pajama Pants',
    category: 'lower',
    price: 349,
    originalPrice: 599,
    colors: [
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Maroon', hex: '#6b1d1d' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.1,
    reviewCount: 92,
    description: 'Soft cotton pajama pants ideal for daily wear and sleeping. Breathable fabric for all-day comfort.',
    material: '100% Cotton, Brushed Interior',
    fit: 'Relaxed Fit',
    washCare: 'Machine wash cold, Line dry',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #1e3a5f 0%, #3d7cc9 100%)',
  },
  {
    id: 'lw-004',
    name: 'Sporty Dry-Fit Lowers',
    category: 'lower',
    price: 499,
    originalPrice: 899,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Royal Blue', hex: '#2b4ea0' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Forest Green', hex: '#228b22' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 134,
    description: 'High-performance dry-fit track pants with 4-way stretch. Designed for intense workouts and sports activities.',
    material: 'Polyester-Spandex, Dry-Fit Technology',
    fit: 'Athletic Fit',
    washCare: 'Machine wash cold, Do not use fabric softener',
    inStock: true,
    badge: 'New',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #2b4ea0 100%)',
  },

  // ---- HALF PANTS ----
  {
    id: 'hp-001',
    name: 'Casual Cotton Shorts',
    category: 'halfpant',
    price: 299,
    originalPrice: 499,
    colors: [
      { name: 'Olive Green', hex: '#4a5d23' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Charcoal', hex: '#36454f' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.3,
    reviewCount: 76,
    description: 'Comfortable cotton shorts with elasticated waistband and deep pockets. Great for summer and casual outings.',
    material: '100% Cotton Twill',
    fit: 'Regular Fit',
    washCare: 'Machine wash cold',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  },
  {
    id: 'hp-002',
    name: 'Athletic Sports Shorts',
    category: 'halfpant',
    price: 349,
    originalPrice: 599,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Royal Blue', hex: '#2b4ea0' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 112,
    description: 'Lightweight athletic shorts with mesh lining and quick-dry fabric. Perfect for gym, running, and sports.',
    material: 'Polyester Mesh, Quick-Dry',
    fit: 'Athletic Fit',
    washCare: 'Machine wash cold, Hang dry',
    inStock: true,
    badge: 'Popular',
    gradient: 'linear-gradient(135deg, #e91e63 0%, #f06292 100%)',
  },
  {
    id: 'hp-003',
    name: 'Bermuda Cargo Shorts',
    category: 'halfpant',
    price: 449,
    originalPrice: 749,
    colors: [
      { name: 'Olive Green', hex: '#4a5d23' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.4,
    reviewCount: 89,
    description: 'Rugged cargo shorts with multiple pockets and durable stitching. Ideal for outdoor adventures and casual wear.',
    material: 'Cotton Canvas, Heavy Duty',
    fit: 'Relaxed Fit',
    washCare: 'Machine wash warm',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #4a5d23 0%, #7cb342 100%)',
  },
  {
    id: 'hp-004',
    name: 'Denim Look Shorts',
    category: 'halfpant',
    price: 399,
    originalPrice: 699,
    colors: [
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Steel Gray', hex: '#71797e' },
      { name: 'Charcoal', hex: '#36454f' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.2,
    reviewCount: 67,
    description: 'Trendy denim-look shorts with stretch comfort. Classic 5-pocket styling meets modern comfort.',
    material: 'Cotton-Spandex Denim, Stretch',
    fit: 'Slim Fit',
    washCare: 'Machine wash cold, Inside out',
    inStock: true,
    badge: 'New',
    gradient: 'linear-gradient(135deg, #1e3a5f 0%, #5b8cc9 100%)',
  },

  // ---- JACKETS ----
  {
    id: 'jk-001',
    name: 'Classic Bomber Jacket',
    category: 'jacket',
    price: 999,
    originalPrice: 1799,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Olive Green', hex: '#4a5d23' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Maroon', hex: '#6b1d1d' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 234,
    description: 'Premium bomber jacket with satin finish exterior and quilted lining. Ribbed collar, cuffs, and hem for a classic look.',
    material: 'Polyester Satin, Quilted Interior',
    fit: 'Regular Fit',
    washCare: 'Dry clean only',
    inStock: true,
    badge: 'Bestseller',
    gradient: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  },
  {
    id: 'jk-002',
    name: 'Denim Trucker Jacket',
    category: 'jacket',
    price: 1199,
    originalPrice: 1999,
    colors: [
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Steel Gray', hex: '#71797e' },
      { name: 'Charcoal', hex: '#36454f' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 167,
    description: 'Classic denim trucker jacket with chest pockets and button closure. Timeless style for all seasons.',
    material: 'Denim, 12 oz Weight',
    fit: 'Regular Fit',
    washCare: 'Machine wash cold, Hang dry',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #1e3a5f 0%, #4facfe 100%)',
  },
  {
    id: 'jk-003',
    name: 'Windbreaker Sport Jacket',
    category: 'jacket',
    price: 899,
    originalPrice: 1499,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Royal Blue', hex: '#2b4ea0' },
      { name: 'Forest Green', hex: '#228b22' },
      { name: 'Charcoal', hex: '#36454f' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.4,
    reviewCount: 143,
    description: 'Lightweight windbreaker jacket with water-resistant coating. Perfect for running, hiking, and windy conditions.',
    material: 'Nylon, Water-Resistant Coating',
    fit: 'Athletic Fit',
    washCare: 'Machine wash cold, Do not tumble dry',
    inStock: true,
    badge: 'New',
    gradient: 'linear-gradient(135deg, #2b4ea0 0%, #00f2fe 100%)',
  },
  {
    id: 'jk-004',
    name: 'Quilted Winter Jacket',
    category: 'jacket',
    price: 1399,
    originalPrice: 2499,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Olive Green', hex: '#4a5d23' },
      { name: 'Burgundy', hex: '#722f37' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 289,
    description: 'Heavy-duty quilted winter jacket with synthetic insulation. Keeps you warm in extreme cold with a stylish silhouette.',
    material: 'Polyester Shell, Synthetic Insulation',
    fit: 'Regular Fit',
    washCare: 'Dry clean recommended',
    inStock: true,
    badge: 'Premium',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #4a5d23 100%)',
  },

  // ---- HOODIES ----
  {
    id: 'hd-001',
    name: 'Classic Pullover Hoodie',
    category: 'hoodie',
    price: 699,
    originalPrice: 1199,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Maroon', hex: '#6b1d1d' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviewCount: 312,
    description: 'Cozy pullover hoodie with kangaroo pocket and drawstring hood. Made from premium French terry for ultimate comfort.',
    material: 'Cotton-Polyester French Terry, 350 GSM',
    fit: 'Relaxed Fit',
    washCare: 'Machine wash cold, Tumble dry low',
    inStock: true,
    badge: 'Bestseller',
    gradient: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
  },
  {
    id: 'hd-002',
    name: 'Zip-Up Sport Hoodie',
    category: 'hoodie',
    price: 799,
    originalPrice: 1399,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Steel Gray', hex: '#71797e' },
      { name: 'Royal Blue', hex: '#2b4ea0' },
      { name: 'Olive Green', hex: '#4a5d23' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.4,
    reviewCount: 178,
    description: 'Full zip hoodie with side pockets and ribbed trim. Versatile layering piece for sports and casual wear.',
    material: 'Polyester-Cotton Blend, Fleece Interior',
    fit: 'Regular Fit',
    washCare: 'Machine wash cold',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #71797e 0%, #a18cd1 100%)',
  },
  {
    id: 'hd-003',
    name: 'Oversized Street Hoodie',
    category: 'hoodie',
    price: 899,
    originalPrice: 1499,
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Mustard', hex: '#c8982e' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 245,
    description: 'Trendy oversized hoodie with drop shoulders and urban street style. Heavy-weight fabric for a premium feel.',
    material: '100% Cotton, 400 GSM, Pre-Shrunk',
    fit: 'Oversized',
    washCare: 'Machine wash cold, Hang dry',
    inStock: true,
    badge: 'Trending',
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #c8982e 100%)',
  },
  {
    id: 'hd-004',
    name: 'Printed Logo Hoodie',
    category: 'hoodie',
    price: 749,
    originalPrice: 1299,
    colors: [
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Burgundy', hex: '#722f37' },
      { name: 'Forest Green', hex: '#228b22' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.3,
    reviewCount: 134,
    description: 'Stylish hoodie with bold chest logo print and premium finish. Perfect for layering in all seasons.',
    material: 'Cotton-Poly Fleece, 320 GSM',
    fit: 'Regular Fit',
    washCare: 'Turn inside out, Machine wash cold',
    inStock: true,
    badge: 'New',
    gradient: 'linear-gradient(135deg, #1e3a5f 0%, #722f37 100%)',
  },

  // ---- KURTAS ----
  {
    id: 'kt-001',
    name: 'Classic Cotton Kurta',
    category: 'kurta',
    price: 549,
    originalPrice: 899,
    colors: [
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Mustard', hex: '#c8982e' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Maroon', hex: '#6b1d1d' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 189,
    description: 'Traditional cotton kurta with mandarin collar and side slits. Perfect for festivals, pujas, and daily ethnic wear.',
    material: '100% Cotton, Handloom Finish',
    fit: 'Regular Fit',
    washCare: 'Hand wash or gentle machine wash',
    inStock: true,
    badge: 'Bestseller',
    gradient: 'linear-gradient(135deg, #c8982e 0%, #f5d799 100%)',
  },
  {
    id: 'kt-002',
    name: 'Embroidered Festive Kurta',
    category: 'kurta',
    price: 799,
    originalPrice: 1399,
    colors: [
      { name: 'Mustard', hex: '#c8982e' },
      { name: 'Maroon', hex: '#6b1d1d' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Black', hex: '#1a1a1a' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 234,
    description: 'Exquisite embroidered kurta with intricate threadwork on collar and placket. Elevate your festive look.',
    material: 'Cotton Silk Blend, Embroidered',
    fit: 'Regular Fit',
    washCare: 'Dry clean only',
    inStock: true,
    badge: 'Premium',
    gradient: 'linear-gradient(135deg, #6b1d1d 0%, #c8982e 100%)',
  },
  {
    id: 'kt-003',
    name: 'Linen Casual Kurta',
    category: 'kurta',
    price: 649,
    originalPrice: 1099,
    colors: [
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Olive Green', hex: '#4a5d23' },
      { name: 'Steel Gray', hex: '#71797e' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.4,
    reviewCount: 112,
    description: 'Lightweight linen kurta for summer comfort. Breathable fabric with minimal design for a clean, modern look.',
    material: 'Pure Linen, Pre-Washed',
    fit: 'Relaxed Fit',
    washCare: 'Hand wash, Hang dry, Iron medium',
    inStock: true,
    badge: '',
    gradient: 'linear-gradient(135deg, #4a5d23 0%, #f5d799 100%)',
  },
  {
    id: 'kt-004',
    name: 'Printed Ethnic Kurta',
    category: 'kurta',
    price: 599,
    originalPrice: 999,
    colors: [
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Maroon', hex: '#6b1d1d' },
      { name: 'Mustard', hex: '#c8982e' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.3,
    reviewCount: 97,
    description: 'Block-printed ethnic kurta with traditional Madhubani-inspired patterns. Celebrate Indian artistry.',
    material: '100% Cotton, Block Printed',
    fit: 'Regular Fit',
    washCare: 'Hand wash cold, Dry in shade',
    inStock: true,
    badge: 'Exclusive',
    gradient: 'linear-gradient(135deg, #1e3a5f 0%, #c8982e 100%)',
  },
  {
    id: 'sw-001',
    name: 'Classic Wool Sweater',
    category: 'sweater',
    price: 599,
    originalPrice: 999,
    colors: [
      { name: 'Maroon', hex: '#6b1d1d' },
      { name: 'Navy Blue', hex: '#1e3a5f' },
      { name: 'Charcoal', hex: '#36454f' },
      { name: 'Forest Green', hex: '#228b22' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 96,
    description: 'Premium wool blend sweater with ribbed cuffs and hem. Keeps you warm and stylish during winter months.',
    material: 'Wool-Acrylic Blend, 400 GSM',
    fit: 'Regular Fit',
    washCare: 'Hand wash cold, Lay flat to dry',
    inStock: true,
    badge: 'Bestseller',
    gradient: 'linear-gradient(135deg, #e17055 0%, #d63031 100%)',
  },
  {
    id: 'sw-002',
    name: 'Cable Knit Pullover',
    category: 'sweater',
    price: 749,
    originalPrice: 1299,
    colors: [
      { name: 'Cream', hex: '#f5e6d3' },
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Burgundy', hex: '#722f37' },
      { name: 'Olive Green', hex: '#4a5d23' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    rating: 4.3,
    reviewCount: 67,
    description: 'Classic cable knit sweater with turtle neck design. Perfect for formal and casual winter wear.',
    material: 'Cotton-Acrylic Blend, Cable Knit',
    fit: 'Regular Fit',
    washCare: 'Machine wash gentle, Do not tumble dry',
    inStock: true,
    badge: 'New',
    gradient: 'linear-gradient(135deg, #f5e6d3 0%, #d4a017 100%)',
  },
];

// Fallback to local products initially
let products = [...localProducts];

// Function to fetch products from API
async function fetchProductsFromAPI() {
  try {
    const API_BASE = window.API_BASE || `/api`;
    const res = await fetch(`${API_BASE}/products?t=` + Date.now(), { cache: 'no-store' });
    if (res.ok) {
      const apiProducts = await res.json();
      if (apiProducts && apiProducts.length > 0) {
        products = apiProducts;
        console.log('✅ Products loaded from database');
        return true;
      }
    }
  } catch (err) {
    console.log('⚠️ Could not connect to API, using local product data');
  }
  return false;
}

// ==================== Sample Reviews ====================
const sampleReviews = [
  {
    id: 'r1',
    name: 'Rahul Sharma',
    location: 'Delhi',
    rating: 5,
    date: '2 days ago',
    comment: 'Excellent quality! The fabric is really soft and comfortable. Will definitely order again in bulk for my shop.',
    verified: true,
  },
  {
    id: 'r2',
    name: 'Priya Patel',
    location: 'Mumbai',
    rating: 4,
    date: '1 week ago',
    comment: 'Good quality at this price point. The stitching is neat and the color doesn\'t fade after washing. Highly recommended.',
    verified: true,
  },
  {
    id: 'r3',
    name: 'Amit Kumar',
    location: 'Patna',
    rating: 5,
    date: '2 weeks ago',
    comment: 'Best wholesale prices I\'ve found! Jaiswal Fashion never disappoints. The delivery was also very fast.',
    verified: true,
  },
  {
    id: 'r4',
    name: 'Sneha Gupta',
    location: 'Lucknow',
    rating: 4,
    date: '3 weeks ago',
    comment: 'The fit is perfect and fabric quality is premium. My customers love these products!',
    verified: true,
  },
  {
    id: 'r5',
    name: 'Vikash Singh',
    location: 'Ranchi',
    rating: 5,
    date: '1 month ago',
    comment: 'Outstanding product! I\'ve been buying from Jaiswal Fashion for 2 years now. Consistent quality every time.',
    verified: true,
  },
  {
    id: 'r6',
    name: 'Anita Devi',
    location: 'Kolkata',
    rating: 4,
    date: '1 month ago',
    comment: 'Very comfortable and looks great. The packaging was also very professional. Good experience overall.',
    verified: false,
  },
];

// ==================== Company Info ====================
const companyInfo = {
  name: 'Jaiswal Fashion',
  tagline: 'Crafted for Comfort. Built for Business.',
  description: 'Jaiswal Fashion delivers premium quality textile garments — T-Shirts, Lowers, Jackets, Kurtas, Hoodies & more — directly from our Madhubani factory to shop owners across India at unbeatable bulk prices.',
  address: 'Mahatha, Ladhania, Madhubani, Bihar - 847232',
  phone: '+91 80843 41453',
  email: 'jaiswalfashions@gmail.com',
  whatsapp: '+91 80843 41453',
  established: '2019',
  factorySize: '25,000 sq ft',
  monthlyCapacity: '50,000+ pieces',
  workers: '200+',
  states: '5+ districts',
  socialMedia: {
    facebook: '#',
    instagram: '#',
    twitter: '#',
    youtube: '#',
  },
};

// ==================== Testimonials ====================
const testimonials = [
  {
    name: 'Rajesh Agarwal',
    role: 'Shop Owner, Patna',
    text: 'I\'ve been sourcing from Jaiswal Fashion for 3 years. Their quality is unmatched at these prices. My customers always come back for more!',
    rating: 5,
  },
  {
    name: 'Suresh Jha',
    role: 'Retailer, Muzaffarpur',
    text: 'Timely delivery, consistent quality, and great wholesale rates. Jaiswal Fashion is my go-to supplier for all garments.',
    rating: 5,
  },
  {
    name: 'Kavita Mishra',
    role: 'Boutique Owner, Darbhanga',
    text: 'The kurta collection is exceptional! My boutique customers love the embroidery work and fabric quality.',
    rating: 4,
  },
  {
    name: 'Deepak Yadav',
    role: 'Wholesale Dealer, Bhagalpur',
    text: 'Best factory rates in Bihar! I\'ve compared with many suppliers but Jaiswal Fashion offers the best value for money.',
    rating: 5,
  },
];

// ==================== Stats ====================
const stats = [
  { number: '10K+', label: 'Product Sell in Monthly' },
  { number: '1000+', label: 'Happy Shopkeepers' },
  { number: '5+', label: 'Districts Covered' },
  { number: '6+', label: 'Years Experience' },
];

// ==================== Why Choose Us ====================
const features = [
  {
    icon: '🏭',
    title: 'Direct from Factory',
    description: 'No middlemen. Get the best prices directly from our Madhubani manufacturing unit.',
  },
  {
    icon: '✨',
    title: 'Premium Quality',
    description: 'Every garment passes 5-point quality check before shipping. Only the best reaches you.',
  },
  {
    icon: '💰',
    title: 'Unbeatable Prices',
    description: 'Wholesale rates starting from ₹199. Bulk discounts available for orders above 100 pieces.',
  },
  {
    icon: '🚚',
    title: 'Pan-India Delivery',
    description: 'Fast and reliable delivery to 5+ districts. Most orders delivered within 5-7 business days.',
  },
  {
    icon: '🔄',
    title: 'Replacement Policy',
    description: '2-day replacement policy on wrong or damaged products. No returns, only replacement for genuine issues.',
  },
  {
    icon: '📞',
    title: '24/7 Support',
    description: 'Dedicated customer support via phone and WhatsApp. We\'re always here to help.',
  },
];

// ==================== Bulk Pricing Tiers ====================
const bulkPricing = [
  { range: '50-99 pieces', discount: '10% OFF', badge: 'Starter' },
  { range: '100-499 pieces', discount: '20% OFF', badge: 'Business' },
  { range: '500-999 pieces', discount: '30% OFF', badge: 'Wholesale' },
  { range: '1000+ pieces', discount: '40% OFF', badge: 'Enterprise' },
];
